version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev  # If you're using Nodemon, or npm start for production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    command: serve dist/
    restart: unless-stopped